Initial structure
gadget-test/org-repo pull request #1
Opened 2015-01-06 17:42 UTC by elbrujohalcon

2015-01-06 18:32 UTC, gadgetci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 25 is too long: "%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL".

2015-01-09 17:35 UTC, gadgetci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 25 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2015-01-09 21:30 UTC, gadgetci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: "%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL".

2015-01-09 21:32 UTC, gadgetci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2015-01-12 19:54 UTC, gadgetci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: "%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL".

2015-01-12 20:01 UTC, gadgetci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: "%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL".

2015-02-04 18:08 UTC, gadgetci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2015-02-04 18:08 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
Warning: variable 'Something' is unused

2015-02-04 20:12 UTC, gadgetci commented on src/org_xref.erl
> +unused() -> unused_function.
Warning: function unused/0 is unused

2015-02-13 20:57 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
Warning: function local_not/1 is unused

2015-02-23 21:09 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad() ->
undefined_function_calls:bad/0 calls undefined function undefined_function_calls:undefined_here/0

2015-02-23 21:09 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
undefined_function_calls:bad/1 calls undefined function other_module:undefined_somewhere_else/1

2015-02-23 21:09 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
undefined_function_calls:bad/1 calls undefined function undefined_functions:undefined_there/0

2015-02-23 21:09 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad() ->
undefined_functions:bad/0 calls undefined function undefined_functions:undefined_here/0

2015-02-23 21:09 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad(1) ->
undefined_functions:bad/1 calls undefined function other_module:undefined_somewhere_else/0

2015-02-23 21:09 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad(1) ->
undefined_functions:bad/1 calls undefined function other_module:undefined_somewhere_else/1

2015-02-23 21:09 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
locals_not_used:local_not/1 is unused local function

2015-02-23 21:09 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad() ->
deprecated_function_calls:bad/0 is unused export

2015-02-23 21:09 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
deprecated_function_calls:bad/1 is unused export

2015-02-23 21:09 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +good() ->
deprecated_function_calls:good/0 is unused export

2015-02-23 21:09 UTC, gadgetci commented on src/xref/exports_not_used.erl
> +export_not(Used) -> local(Used), {it, is, not Used}.
exports_not_used:export_not/1 is unused export

2015-02-23 21:09 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad() ->
ignore_xref:bad/0 is unused export

2015-02-23 21:09 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad(1) ->
ignore_xref:bad/1 is unused export

2015-02-23 21:09 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +good() ->
ignore_xref:good/0 is unused export

2015-02-23 21:09 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +exported() -> local(true), {it, is, exports_not_used:exported()}.
locals_not_used:exported/0 is unused export

2015-02-23 21:09 UTC, gadgetci commented on src/org.erl
> +start() -> application:ensure_all_started(org).
org:start/0 is unused export

2015-02-23 21:09 UTC, gadgetci commented on src/org.erl
> +stop() -> application:stop(org).
org:stop/0 is unused export

2015-02-23 21:09 UTC, gadgetci commented on src/org_warning.erl
> +my_fun(X) ->
org_warning:my_fun/1 is unused export

2015-02-23 21:09 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
org_warning:warning/1 is unused export

2015-02-23 21:09 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad() ->
undefined_function_calls:bad/0 is unused export

2015-02-23 21:09 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad() ->
undefined_functions:bad/0 is unused export

2015-02-23 21:09 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad() ->
deprecated_function_calls:bad/0 calls deprecated function deprecated_functions:deprecated/0

2015-02-23 21:09 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
deprecated_function_calls:bad/1 calls deprecated function deprecated_function_calls:internal/0

2015-02-23 21:09 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
deprecated_function_calls:bad/1 calls deprecated function deprecated_functions:deprecated/1

2015-02-24 10:21 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad() ->
deprecated_function_calls:bad/0 calls deprecated function deprecated_functions:deprecated/0

2015-02-24 10:21 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
deprecated_function_calls:bad/1 calls deprecated function deprecated_function_calls:internal/0

2015-02-24 10:22 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
deprecated_function_calls:bad/1 calls deprecated function deprecated_functions:deprecated/1

2015-02-24 10:22 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad() ->
ignore_xref:bad/0 calls deprecated function deprecated_functions:deprecated/0

2015-02-24 10:22 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad(1) ->
ignore_xref:bad/1 calls deprecated function ignore_xref:internal/0

2015-02-24 10:22 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +internal() -> {this, is, deprecated}.
deprecated_function_calls:internal/0 is deprecated function

2015-02-24 10:22 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated() -> {this, function, is, deprecated}.
deprecated_functions:deprecated/0 is deprecated function

2015-02-24 10:22 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated(SomeDay) -> {this, function, will, be, removed, SomeDay}.
deprecated_functions:deprecated/1 is deprecated function

2015-02-24 10:22 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +internal() -> {this, is, deprecated}.
ignore_xref:internal/0 is deprecated function

2015-02-24 10:46 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad() ->
According to **Xref**:
> `undefined_function_calls:bad/0` calls undefined function `undefined_function_calls:undefined_here/0`

2015-02-24 10:46 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `undefined_function_calls:bad/1` calls undefined function `other_module:undefined_somewhere_else/1`

2015-02-24 10:46 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `undefined_function_calls:bad/1` calls undefined function `undefined_functions:undefined_there/0`

2015-02-24 10:46 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad() ->
According to **Xref**:
> `undefined_functions:bad/0` calls undefined function `undefined_functions:undefined_here/0`

2015-02-24 10:46 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad(1) ->
According to **Xref**:
> `undefined_functions:bad/1` calls undefined function `other_module:undefined_somewhere_else/0`

2015-02-24 10:46 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad(1) ->
According to **Xref**:
> `undefined_functions:bad/1` calls undefined function `other_module:undefined_somewhere_else/1`

2015-02-24 10:46 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Xref**:
> `locals_not_used:local_not/1` is an unused local function

2015-02-24 10:46 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad() ->
According to **Xref**:
> `deprecated_function_calls:bad/0` is an unused export

2015-02-24 10:46 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` is an unused export

2015-02-24 10:46 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +good() ->
According to **Xref**:
> `deprecated_function_calls:good/0` is an unused export

2015-02-24 10:46 UTC, gadgetci commented on src/xref/exports_not_used.erl
> +export_not(Used) -> local(Used), {it, is, not Used}.
According to **Xref**:
> `exports_not_used:export_not/1` is an unused export

2015-02-24 10:46 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad() ->
According to **Xref**:
> `ignore_xref:bad/0` is an unused export

2015-02-24 10:46 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad(1) ->
According to **Xref**:
> `ignore_xref:bad/1` is an unused export

2015-02-24 10:46 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +good() ->
According to **Xref**:
> `ignore_xref:good/0` is an unused export

2015-02-24 10:46 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +exported() -> local(true), {it, is, exports_not_used:exported()}.
According to **Xref**:
> `locals_not_used:exported/0` is an unused export

2015-02-24 10:46 UTC, gadgetci commented on src/org.erl
> +start() -> application:ensure_all_started(org).
According to **Xref**:
> `org:start/0` is an unused export

2015-02-24 10:47 UTC, gadgetci commented on src/org.erl
> +stop() -> application:stop(org).
According to **Xref**:
> `org:stop/0` is an unused export

2015-02-24 10:47 UTC, gadgetci commented on src/org_warning.erl
> +my_fun(X) ->
According to **Xref**:
> `org_warning:my_fun/1` is an unused export

2015-02-24 10:47 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
According to **Xref**:
> `org_warning:warning/1` is an unused export

2015-02-24 10:47 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad() ->
According to **Xref**:
> `undefined_function_calls:bad/0` is an unused export

2015-02-24 10:47 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad() ->
According to **Xref**:
> `undefined_functions:bad/0` is an unused export

2015-02-24 10:47 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad() ->
According to **Xref**:
> `deprecated_function_calls:bad/0` calls deprecated function `deprecated_functions:deprecated/0`

2015-02-24 10:47 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` calls deprecated function `deprecated_function_calls:internal/0`

2015-02-24 10:47 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` calls deprecated function `deprecated_functions:deprecated/1`

2015-02-24 10:56 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad() ->
According to **Xref**:
> `undefined_function_calls:bad/0` calls undefined function `undefined_function_calls:undefined_here/0`

2015-02-24 10:56 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `undefined_function_calls:bad/1` calls undefined function `other_module:undefined_somewhere_else/1`

2015-02-24 10:56 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `undefined_function_calls:bad/1` calls undefined function `undefined_functions:undefined_there/0`

2015-02-24 10:56 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad() ->
According to **Xref**:
> `undefined_functions:bad/0` calls undefined function `undefined_functions:undefined_here/0`

2015-02-24 10:56 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad(1) ->
According to **Xref**:
> `undefined_functions:bad/1` calls undefined function `other_module:undefined_somewhere_else/0`

2015-02-24 10:56 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad(1) ->
According to **Xref**:
> `undefined_functions:bad/1` calls undefined function `other_module:undefined_somewhere_else/1`

2015-02-24 10:56 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Xref**:
> `locals_not_used:local_not/1` is an unused local function

2015-02-24 10:56 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad() ->
According to **Xref**:
> `deprecated_function_calls:bad/0` is an unused export

2015-02-24 10:56 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` is an unused export

2015-02-24 10:56 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +good() ->
According to **Xref**:
> `deprecated_function_calls:good/0` is an unused export

2015-02-24 10:56 UTC, gadgetci commented on src/xref/exports_not_used.erl
> +export_not(Used) -> local(Used), {it, is, not Used}.
According to **Xref**:
> `exports_not_used:export_not/1` is an unused export

2015-02-24 10:56 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad() ->
According to **Xref**:
> `ignore_xref:bad/0` is an unused export

2015-02-24 10:56 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad(1) ->
According to **Xref**:
> `ignore_xref:bad/1` is an unused export

2015-02-24 10:56 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +good() ->
According to **Xref**:
> `ignore_xref:good/0` is an unused export

2015-02-24 10:56 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +exported() -> local(true), {it, is, exports_not_used:exported()}.
According to **Xref**:
> `locals_not_used:exported/0` is an unused export

2015-02-24 10:56 UTC, gadgetci commented on src/org.erl
> +start() -> application:ensure_all_started(org).
According to **Xref**:
> `org:start/0` is an unused export

2015-02-24 10:56 UTC, gadgetci commented on src/org.erl
> +stop() -> application:stop(org).
According to **Xref**:
> `org:stop/0` is an unused export

2015-02-24 10:56 UTC, gadgetci commented on src/org_warning.erl
> +my_fun(X) ->
According to **Xref**:
> `org_warning:my_fun/1` is an unused export

2015-02-24 10:56 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
According to **Xref**:
> `org_warning:warning/1` is an unused export

2015-02-24 10:56 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad() ->
According to **Xref**:
> `undefined_function_calls:bad/0` is an unused export

2015-02-24 10:56 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad() ->
According to **Xref**:
> `undefined_functions:bad/0` is an unused export

2015-02-24 10:56 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad() ->
According to **Xref**:
> `deprecated_function_calls:bad/0` calls deprecated function `deprecated_functions:deprecated/0`

2015-02-24 10:56 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` calls deprecated function `deprecated_function_calls:internal/0`

2015-02-24 10:56 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` calls deprecated function `deprecated_functions:deprecated/1`

2015-02-25 17:49 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad() ->
According to **Xref**:
> `ignore_xref:bad/0` calls deprecated function `deprecated_functions:deprecated/0`

2015-02-25 17:49 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad(1) ->
According to **Xref**:
> `ignore_xref:bad/1` calls deprecated function `ignore_xref:internal/0`

2015-02-25 17:49 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `deprecated_function_calls:internal/0` is deprecated

2015-02-25 17:49 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated() -> {this, function, is, deprecated}.
According to **Xref**:
> `deprecated_functions:deprecated/0` is deprecated

2015-02-25 17:49 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated(SomeDay) -> {this, function, will, be, removed, SomeDay}.
According to **Xref**:
> `deprecated_functions:deprecated/1` is deprecated

2015-02-25 17:49 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `ignore_xref:internal/0` is deprecated

2015-02-27 14:37 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad() ->
According to **Xref**:
> `ignore_xref:bad/0` calls deprecated function `deprecated_functions:deprecated/0`

2015-02-27 14:37 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad(1) ->
According to **Xref**:
> `ignore_xref:bad/1` calls deprecated function `ignore_xref:internal/0`

2015-02-27 14:37 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `deprecated_function_calls:internal/0` is deprecated

2015-02-27 14:37 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated() -> {this, function, is, deprecated}.
According to **Xref**:
> `deprecated_functions:deprecated/0` is deprecated

2015-02-27 14:37 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated(SomeDay) -> {this, function, will, be, removed, SomeDay}.
According to **Xref**:
> `deprecated_functions:deprecated/1` is deprecated

2015-02-27 14:37 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `ignore_xref:internal/0` is deprecated

2015-02-27 14:40 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +good() ->
According to **Xref**:
> `deprecated_function_calls:good/0` is an unused export

2015-02-27 14:40 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad() ->
According to **Xref**:
> `ignore_xref:bad/0` is an unused export

2015-02-27 14:40 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad(1) ->
According to **Xref**:
> `ignore_xref:bad/1` is an unused export

2015-02-27 14:40 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad() ->
According to **Xref**:
> `ignore_xref:bad/0` calls deprecated function `deprecated_functions:deprecated/0`

2015-02-27 14:40 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad(1) ->
According to **Xref**:
> `ignore_xref:bad/1` calls deprecated function `ignore_xref:internal/0`

2015-02-27 14:40 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `ignore_xref:internal/0` is deprecated

2015-02-27 14:43 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad() ->
According to **Xref**:
> `undefined_function_calls:bad/0` calls undefined function `undefined_function_calls:undefined_here/0`

2015-02-27 14:43 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `undefined_function_calls:bad/1` calls undefined function `other_module:undefined_somewhere_else/1`

2015-02-27 14:43 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `undefined_function_calls:bad/1` calls undefined function `undefined_functions:undefined_there/0`

2015-02-27 14:43 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad() ->
According to **Xref**:
> `undefined_functions:bad/0` calls undefined function `undefined_functions:undefined_here/0`

2015-02-27 14:43 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad(1) ->
According to **Xref**:
> `undefined_functions:bad/1` calls undefined function `other_module:undefined_somewhere_else/0`

2015-02-27 14:43 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad(1) ->
According to **Xref**:
> `undefined_functions:bad/1` calls undefined function `other_module:undefined_somewhere_else/1`

2015-02-27 14:43 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Xref**:
> `locals_not_used:local_not/1` is an unused local function

2015-02-27 14:43 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad() ->
According to **Xref**:
> `deprecated_function_calls:bad/0` is an unused export

2015-02-27 14:43 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` is an unused export

2015-02-27 14:43 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +good() ->
According to **Xref**:
> `deprecated_function_calls:good/0` is an unused export

2015-02-27 14:43 UTC, gadgetci commented on src/xref/exports_not_used.erl
> +export_not(Used) -> local(Used), {it, is, not Used}.
According to **Xref**:
> `exports_not_used:export_not/1` is an unused export

2015-02-27 14:43 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad() ->
According to **Xref**:
> `ignore_xref:bad/0` is an unused export

2015-02-27 14:43 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad(1) ->
According to **Xref**:
> `ignore_xref:bad/1` is an unused export

2015-02-27 14:43 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +good() ->
According to **Xref**:
> `ignore_xref:good/0` is an unused export

2015-02-27 14:43 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +exported() -> local(true), {it, is, exports_not_used:exported()}.
According to **Xref**:
> `locals_not_used:exported/0` is an unused export

2015-02-27 14:43 UTC, gadgetci commented on src/org.erl
> +start() -> application:ensure_all_started(org).
According to **Xref**:
> `org:start/0` is an unused export

2015-02-27 14:43 UTC, gadgetci commented on src/org.erl
> +stop() -> application:stop(org).
According to **Xref**:
> `org:stop/0` is an unused export

2015-02-27 14:43 UTC, gadgetci commented on src/org_warning.erl
> +my_fun(X) ->
According to **Xref**:
> `org_warning:my_fun/1` is an unused export

2015-02-27 14:43 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
According to **Xref**:
> `org_warning:warning/1` is an unused export

2015-02-27 14:43 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad() ->
According to **Xref**:
> `undefined_function_calls:bad/0` is an unused export

2015-02-27 14:43 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad() ->
According to **Xref**:
> `undefined_functions:bad/0` is an unused export

2015-02-27 14:43 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad() ->
According to **Xref**:
> `deprecated_function_calls:bad/0` calls deprecated function `deprecated_functions:deprecated/0`

2015-02-27 14:43 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` calls deprecated function `deprecated_function_calls:internal/0`

2015-02-27 14:43 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` calls deprecated function `deprecated_functions:deprecated/1`

2015-02-27 14:46 UTC, gadgetci commented
According to **Xref**:
> `undefined_function_calls:undefined_here/0` is not defined as a function

2015-02-27 14:46 UTC, gadgetci commented
According to **Xref**:
> `undefined_functions:undefined_here/0` is not defined as a function

2015-02-27 14:46 UTC, gadgetci commented
According to **Xref**:
> `undefined_functions:undefined_there/0` is not defined as a function

2015-02-27 14:46 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad() ->
According to **Xref**:
> `ignore_xref:bad/0` calls deprecated function `deprecated_functions:deprecated/0`

2015-02-27 14:46 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad(1) ->
According to **Xref**:
> `ignore_xref:bad/1` calls deprecated function `ignore_xref:internal/0`

2015-02-27 14:46 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `deprecated_function_calls:internal/0` is deprecated

2015-02-27 14:46 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated() -> {this, function, is, deprecated}.
According to **Xref**:
> `deprecated_functions:deprecated/0` is deprecated

2015-02-27 14:46 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated(SomeDay) -> {this, function, will, be, removed, SomeDay}.
According to **Xref**:
> `deprecated_functions:deprecated/1` is deprecated

2015-02-27 14:46 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `ignore_xref:internal/0` is deprecated

2015-02-27 14:53 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad() ->
According to **Xref**:
> `ignore_xref:bad/0` calls deprecated function `deprecated_functions:deprecated/0`

2015-02-27 14:53 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad(1) ->
According to **Xref**:
> `ignore_xref:bad/1` calls deprecated function `ignore_xref:internal/0`

2015-02-27 14:53 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `deprecated_function_calls:internal/0` is deprecated

2015-02-27 14:53 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated() -> {this, function, is, deprecated}.
According to **Xref**:
> `deprecated_functions:deprecated/0` is deprecated

2015-02-27 14:53 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated(SomeDay) -> {this, function, will, be, removed, SomeDay}.
According to **Xref**:
> `deprecated_functions:deprecated/1` is deprecated

2015-02-27 14:53 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `ignore_xref:internal/0` is deprecated

2015-02-27 14:56 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad() ->
According to **Xref**:
> `undefined_function_calls:bad/0` calls undefined function `undefined_function_calls:undefined_here/0`

2015-02-27 14:56 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `undefined_function_calls:bad/1` calls undefined function `other_module:undefined_somewhere_else/1`

2015-02-27 14:56 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `undefined_function_calls:bad/1` calls undefined function `undefined_functions:undefined_there/0`

2015-02-27 14:56 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad() ->
According to **Xref**:
> `undefined_functions:bad/0` calls undefined function `undefined_functions:undefined_here/0`

2015-02-27 14:56 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad(1) ->
According to **Xref**:
> `undefined_functions:bad/1` calls undefined function `other_module:undefined_somewhere_else/0`

2015-02-27 14:56 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad(1) ->
According to **Xref**:
> `undefined_functions:bad/1` calls undefined function `other_module:undefined_somewhere_else/1`

2015-02-27 14:56 UTC, gadgetci commented
According to **Xref**:
> `undefined_function_calls:undefined_here/0` is not defined as a function

2015-02-27 14:56 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Xref**:
> `locals_not_used:local_not/1` is an unused local function

2015-02-27 14:56 UTC, gadgetci commented
According to **Xref**:
> `undefined_functions:undefined_here/0` is not defined as a function

2015-02-27 14:56 UTC, gadgetci commented
According to **Xref**:
> `undefined_functions:undefined_there/0` is not defined as a function

2015-02-27 14:56 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad() ->
According to **Xref**:
> `deprecated_function_calls:bad/0` is an unused export

2015-02-27 14:56 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` is an unused export

2015-02-27 14:56 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +good() ->
According to **Xref**:
> `deprecated_function_calls:good/0` is an unused export

2015-02-27 14:56 UTC, gadgetci commented on src/xref/exports_not_used.erl
> +export_not(Used) -> local(Used), {it, is, not Used}.
According to **Xref**:
> `exports_not_used:export_not/1` is an unused export

2015-02-27 14:56 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad() ->
According to **Xref**:
> `ignore_xref:bad/0` is an unused export

2015-02-27 14:56 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad(1) ->
According to **Xref**:
> `ignore_xref:bad/1` is an unused export

2015-02-27 14:56 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +good() ->
According to **Xref**:
> `ignore_xref:good/0` is an unused export

2015-02-27 14:56 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +exported() -> local(true), {it, is, exports_not_used:exported()}.
According to **Xref**:
> `locals_not_used:exported/0` is an unused export

2015-02-27 14:56 UTC, gadgetci commented on src/org.erl
> +start() -> application:ensure_all_started(org).
According to **Xref**:
> `org:start/0` is an unused export

2015-02-27 14:56 UTC, gadgetci commented on src/org.erl
> +stop() -> application:stop(org).
According to **Xref**:
> `org:stop/0` is an unused export

2015-02-27 14:56 UTC, gadgetci commented on src/org_warning.erl
> +my_fun(X) ->
According to **Xref**:
> `org_warning:my_fun/1` is an unused export

2015-02-27 14:56 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
According to **Xref**:
> `org_warning:warning/1` is an unused export

2015-02-27 14:56 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad() ->
According to **Xref**:
> `undefined_function_calls:bad/0` is an unused export

2015-02-27 14:56 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad() ->
According to **Xref**:
> `undefined_functions:bad/0` is an unused export

2015-03-04 17:02 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `ignore_xref:internal/0` is deprecated

2015-03-04 17:03 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated(SomeDay) -> {this, function, will, be, removed, SomeDay}.
According to **Xref**:
> `deprecated_functions:deprecated/1` is deprecated

2015-03-04 17:05 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated() -> {this, function, is, deprecated}.
According to **Xref**:
> `deprecated_functions:deprecated/0` is deprecated

2015-03-04 17:06 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `deprecated_function_calls:internal/0` is deprecated

2015-03-04 17:08 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad(1) ->
According to **Xref**:
> `ignore_xref:bad/1` calls deprecated function `ignore_xref:internal/0`

2015-03-04 17:11 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `ignore_xref:internal/0` is deprecated

2015-03-04 17:15 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated(SomeDay) -> {this, function, will, be, removed, SomeDay}.
According to **Xref**:
> `deprecated_functions:deprecated/1` is deprecated

2015-03-04 17:16 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated() -> {this, function, is, deprecated}.
According to **Xref**:
> `deprecated_functions:deprecated/0` is deprecated

2015-03-04 17:22 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `deprecated_function_calls:internal/0` is deprecated

2015-03-04 17:25 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `ignore_xref:internal/0` is deprecated

2015-03-04 17:30 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `ignore_xref:internal/0` is deprecated

2015-03-04 17:32 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated(SomeDay) -> {this, function, will, be, removed, SomeDay}.
According to **Xref**:
> `deprecated_functions:deprecated/1` is deprecated

2015-03-04 17:33 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated() -> {this, function, is, deprecated}.
According to **Xref**:
> `deprecated_functions:deprecated/0` is deprecated

2015-03-04 17:34 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `deprecated_function_calls:internal/0` is deprecated

2015-03-04 17:36 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad() ->
According to **Xref**:
> `undefined_function_calls:bad/0` calls undefined function `undefined_function_calls:undefined_here/0`

2015-03-04 17:40 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `deprecated_function_calls:internal/0` is deprecated

2015-03-04 17:40 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad() ->
According to **Xref**:
> `undefined_functions:bad/0` is an unused export

2015-03-04 17:40 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Xref**:
> `locals_not_used:local_not/1` is an unused local function

2015-03-04 17:40 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad() ->
According to **Xref**:
> `deprecated_function_calls:bad/0` is an unused export

2015-03-04 17:40 UTC, gadgetci commented
According to **Xref**:
> `undefined_function_calls:undefined_here/0` is not defined as a function

2015-03-04 17:40 UTC, gadgetci commented
According to **Xref**:
> `undefined_functions:undefined_there/0` is not defined as a function

2015-03-04 17:40 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `undefined_function_calls:bad/1` calls undefined function `undefined_functions:undefined_there/0`

2015-03-04 17:40 UTC, gadgetci commented on src/org_warning.erl
> +my_fun(X) ->
According to **Xref**:
> `org_warning:my_fun/1` is an unused export

2015-03-04 17:40 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated(SomeDay) -> {this, function, will, be, removed, SomeDay}.
According to **Xref**:
> `deprecated_functions:deprecated/1` is deprecated

2015-03-04 17:40 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +exported() -> local(true), {it, is, exports_not_used:exported()}.
According to **Xref**:
> `locals_not_used:exported/0` is an unused export

2015-03-04 17:40 UTC, gadgetci commented on src/xref/exports_not_used.erl
> +export_not(Used) -> local(Used), {it, is, not Used}.
According to **Xref**:
> `exports_not_used:export_not/1` is an unused export

2015-03-04 17:40 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad() ->
According to **Xref**:
> `undefined_function_calls:bad/0` is an unused export

2015-03-04 17:40 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` calls deprecated function `deprecated_function_calls:internal/0`

2015-03-04 17:40 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
According to **Xref**:
> `org_warning:warning/1` is an unused export

2015-03-04 17:40 UTC, gadgetci commented on src/org.erl
> +stop() -> application:stop(org).
According to **Xref**:
> `org:stop/0` is an unused export

2015-03-04 17:40 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +good() ->
According to **Xref**:
> `ignore_xref:good/0` is an unused export

2015-03-04 17:40 UTC, gadgetci commented
According to **Xref**:
> `undefined_functions:undefined_here/0` is not defined as a function

2015-03-04 17:40 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad() ->
According to **Xref**:
> `deprecated_function_calls:bad/0` calls deprecated function `deprecated_functions:deprecated/0`

2015-03-04 17:40 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad(1) ->
According to **Xref**:
> `undefined_functions:bad/1` calls undefined function `other_module:undefined_somewhere_else/0`

2015-03-04 17:40 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad(1) ->
According to **Xref**:
> `ignore_xref:bad/1` calls deprecated function `ignore_xref:internal/0`

2015-03-04 17:40 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` is an unused export

2015-03-04 17:40 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad(1) ->
According to **Xref**:
> `ignore_xref:bad/1` is an unused export

2015-03-04 17:40 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +good() ->
According to **Xref**:
> `deprecated_function_calls:good/0` is an unused export

2015-03-04 17:40 UTC, gadgetci commented on src/org.erl
> +start() -> application:ensure_all_started(org).
According to **Xref**:
> `org:start/0` is an unused export

2015-03-04 17:41 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `ignore_xref:internal/0` is deprecated

2015-03-04 17:41 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad() ->
According to **Xref**:
> `undefined_functions:bad/0` calls undefined function `undefined_functions:undefined_here/0`

2015-03-04 17:41 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated() -> {this, function, is, deprecated}.
According to **Xref**:
> `deprecated_functions:deprecated/0` is deprecated

2015-03-04 17:41 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad() ->
According to **Xref**:
> `ignore_xref:bad/0` is an unused export

2015-03-04 17:41 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `undefined_function_calls:bad/1` calls undefined function `other_module:undefined_somewhere_else/1`

2015-03-04 17:41 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad(1) ->
According to **Xref**:
> `undefined_functions:bad/1` calls undefined function `other_module:undefined_somewhere_else/1`

2015-03-04 17:41 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad() ->
According to **Xref**:
> `ignore_xref:bad/0` calls deprecated function `deprecated_functions:deprecated/0`

2015-03-04 17:41 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` calls deprecated function `deprecated_functions:deprecated/1`

2015-03-04 17:45 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad() ->
According to **Xref**:
> `ignore_xref:bad/0` is an unused export

2015-03-04 17:45 UTC, gadgetci commented on src/org_warning.erl
> +my_fun(X) ->
According to **Xref**:
> `org_warning:my_fun/1` is an unused export

2015-03-04 17:45 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `undefined_function_calls:bad/1` calls undefined function `other_module:undefined_somewhere_else/1`

2015-03-04 17:45 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad() ->
According to **Xref**:
> `undefined_functions:bad/0` is an unused export

2015-03-04 17:45 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad(1) ->
According to **Xref**:
> `ignore_xref:bad/1` calls deprecated function `ignore_xref:internal/0`

2015-03-04 17:45 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` is an unused export

2015-03-04 17:45 UTC, gadgetci commented on src/org.erl
> +start() -> application:ensure_all_started(org).
According to **Xref**:
> `org:start/0` is an unused export

2015-03-04 17:45 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `deprecated_function_calls:internal/0` is deprecated

2015-03-04 17:45 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad(1) ->
According to **Xref**:
> `undefined_functions:bad/1` calls undefined function `other_module:undefined_somewhere_else/1`

2015-03-04 17:45 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad(1) ->
According to **Xref**:
> `undefined_functions:bad/1` calls undefined function `other_module:undefined_somewhere_else/0`

2015-03-04 17:45 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +good() ->
According to **Xref**:
> `deprecated_function_calls:good/0` is an unused export

2015-03-04 17:45 UTC, gadgetci commented
According to **Xref**:
> `undefined_functions:undefined_here/0` is not defined as a function

2015-03-04 17:45 UTC, gadgetci commented
According to **Xref**:
> `undefined_functions:undefined_there/0` is not defined as a function

2015-03-04 17:45 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated() -> {this, function, is, deprecated}.
According to **Xref**:
> `deprecated_functions:deprecated/0` is deprecated

2015-03-04 17:45 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `ignore_xref:internal/0` is deprecated

2015-03-04 17:45 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad() ->
According to **Xref**:
> `undefined_function_calls:bad/0` is an unused export

2015-03-04 17:45 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +good() ->
According to **Xref**:
> `ignore_xref:good/0` is an unused export

2015-03-04 17:45 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated(SomeDay) -> {this, function, will, be, removed, SomeDay}.
According to **Xref**:
> `deprecated_functions:deprecated/1` is deprecated

2015-03-04 17:45 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +exported() -> local(true), {it, is, exports_not_used:exported()}.
According to **Xref**:
> `locals_not_used:exported/0` is an unused export

2015-03-04 17:45 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` calls deprecated function `deprecated_function_calls:internal/0`

2015-03-04 17:45 UTC, gadgetci commented
According to **Xref**:
> `undefined_function_calls:undefined_here/0` is not defined as a function

2015-03-04 17:45 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
According to **Xref**:
> `org_warning:warning/1` is an unused export

2015-03-04 17:45 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `undefined_function_calls:bad/1` calls undefined function `undefined_functions:undefined_there/0`

2015-03-04 17:45 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad() ->
According to **Xref**:
> `undefined_functions:bad/0` calls undefined function `undefined_functions:undefined_here/0`

2015-03-04 17:46 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` calls deprecated function `deprecated_functions:deprecated/1`

2015-03-04 17:46 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad() ->
According to **Xref**:
> `undefined_function_calls:bad/0` calls undefined function `undefined_function_calls:undefined_here/0`

2015-03-04 17:46 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad() ->
According to **Xref**:
> `deprecated_function_calls:bad/0` is an unused export

2015-03-04 17:46 UTC, gadgetci commented on src/xref/exports_not_used.erl
> +export_not(Used) -> local(Used), {it, is, not Used}.
According to **Xref**:
> `exports_not_used:export_not/1` is an unused export

2015-03-04 17:46 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Xref**:
> `locals_not_used:local_not/1` is an unused local function

2015-03-04 17:46 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad() ->
According to **Xref**:
> `deprecated_function_calls:bad/0` calls deprecated function `deprecated_functions:deprecated/0`

2015-03-04 17:46 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad(1) ->
According to **Xref**:
> `ignore_xref:bad/1` is an unused export

2015-03-04 17:46 UTC, gadgetci commented on src/org.erl
> +stop() -> application:stop(org).
According to **Xref**:
> `org:stop/0` is an unused export

2015-03-04 17:46 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad() ->
According to **Xref**:
> `ignore_xref:bad/0` calls deprecated function `deprecated_functions:deprecated/0`

2015-03-04 18:11 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad(1) ->
According to **Xref**:
> `ignore_xref:bad/1` calls deprecated function `ignore_xref:internal/0`

2015-03-04 18:11 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Xref**:
> `locals_not_used:local_not/1` is an unused local function

2015-03-04 18:11 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad(1) ->
According to **Xref**:
> `undefined_functions:bad/1` calls undefined function `other_module:undefined_somewhere_else/1`

2015-03-04 18:11 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated(SomeDay) -> {this, function, will, be, removed, SomeDay}.
According to **Xref**:
> `deprecated_functions:deprecated/1` is deprecated

2015-03-04 18:11 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `ignore_xref:internal/0` is deprecated

2015-03-04 18:11 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad() ->
According to **Xref**:
> `undefined_functions:bad/0` is an unused export

2015-03-04 18:11 UTC, gadgetci commented on src/org.erl
> +stop() -> application:stop(org).
According to **Xref**:
> `org:stop/0` is an unused export

2015-03-04 18:11 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad() ->
According to **Xref**:
> `undefined_functions:bad/0` calls undefined function `undefined_functions:undefined_here/0`

2015-03-04 18:11 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `undefined_function_calls:bad/1` calls undefined function `other_module:undefined_somewhere_else/1`

2015-03-04 18:11 UTC, gadgetci commented
According to **Xref**:
> `undefined_function_calls:undefined_here/0` is not defined as a function

2015-03-04 18:11 UTC, gadgetci commented
According to **Xref**:
> `undefined_functions:undefined_here/0` is not defined as a function

2015-03-04 18:11 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad(1) ->
According to **Xref**:
> `undefined_functions:bad/1` calls undefined function `other_module:undefined_somewhere_else/0`

2015-03-04 18:11 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +good() ->
According to **Xref**:
> `deprecated_function_calls:good/0` is an unused export

2015-03-04 18:11 UTC, gadgetci commented
According to **Xref**:
> `undefined_functions:undefined_there/0` is not defined as a function

2015-03-04 18:11 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
According to **Xref**:
> `org_warning:warning/1` is an unused export

2015-03-04 18:11 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad() ->
According to **Xref**:
> `deprecated_function_calls:bad/0` is an unused export

2015-03-04 18:11 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +exported() -> local(true), {it, is, exports_not_used:exported()}.
According to **Xref**:
> `locals_not_used:exported/0` is an unused export

2015-03-04 18:11 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated() -> {this, function, is, deprecated}.
According to **Xref**:
> `deprecated_functions:deprecated/0` is deprecated

2015-03-04 18:11 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad() ->
According to **Xref**:
> `ignore_xref:bad/0` is an unused export

2015-03-04 18:11 UTC, gadgetci commented on src/org.erl
> +start() -> application:ensure_all_started(org).
According to **Xref**:
> `org:start/0` is an unused export

2015-03-04 18:11 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `deprecated_function_calls:internal/0` is deprecated

2015-03-04 18:11 UTC, gadgetci commented on src/xref/exports_not_used.erl
> +export_not(Used) -> local(Used), {it, is, not Used}.
According to **Xref**:
> `exports_not_used:export_not/1` is an unused export

2015-03-04 18:11 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +good() ->
According to **Xref**:
> `ignore_xref:good/0` is an unused export

2015-03-04 18:11 UTC, gadgetci commented on src/org_warning.erl
> +my_fun(X) ->
According to **Xref**:
> `org_warning:my_fun/1` is an unused export

2015-03-04 18:12 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad() ->
According to **Xref**:
> `deprecated_function_calls:bad/0` calls deprecated function `deprecated_functions:deprecated/0`

2015-03-04 18:12 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad(1) ->
According to **Xref**:
> `ignore_xref:bad/1` is an unused export

2015-03-04 18:12 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad() ->
According to **Xref**:
> `ignore_xref:bad/0` calls deprecated function `deprecated_functions:deprecated/0`

2015-03-04 18:12 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `undefined_function_calls:bad/1` calls undefined function `undefined_functions:undefined_there/0`

2015-03-04 18:12 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` is an unused export

2015-03-04 18:12 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad() ->
According to **Xref**:
> `undefined_function_calls:bad/0` is an unused export

2015-03-05 13:43 UTC, gadgetci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2015-03-05 13:43 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
Warning: function local_not/1 is unused

2015-03-05 13:43 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
Warning: variable 'Something' is unused

2015-03-05 20:02 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `deprecated_function_calls:internal/0` is deprecated

2015-03-05 20:02 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `undefined_function_calls:bad/1` calls undefined function `other_module:undefined_somewhere_else/1`

2015-03-05 20:02 UTC, gadgetci commented
According to **Xref**:
> `undefined_functions:undefined_here/0` is not defined as a function

2015-03-05 20:02 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad() ->
According to **Xref**:
> `deprecated_function_calls:bad/0` is an unused export

2015-03-05 20:02 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad() ->
According to **Xref**:
> `undefined_function_calls:bad/0` is an unused export

2015-03-05 20:02 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
According to **Xref**:
> `org_warning:warning/1` is an unused export

2015-03-05 20:02 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad() ->
According to **Xref**:
> `ignore_xref:bad/0` calls deprecated function `deprecated_functions:deprecated/0`

2015-03-05 20:02 UTC, gadgetci commented
According to **Xref**:
> `undefined_function_calls:undefined_here/0` is not defined as a function

2015-03-05 20:02 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad() ->
According to **Xref**:
> `undefined_function_calls:bad/0` calls undefined function `undefined_function_calls:undefined_here/0`

2015-03-05 20:02 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Xref**:
> `locals_not_used:local_not/1` is an unused local function

2015-03-05 20:02 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +exported() -> local(true), {it, is, exports_not_used:exported()}.
According to **Xref**:
> `locals_not_used:exported/0` is an unused export

2015-03-05 20:02 UTC, gadgetci commented on src/org.erl
> +start() -> application:ensure_all_started(org).
According to **Xref**:
> `org:start/0` is an unused export

2015-03-05 20:02 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated(SomeDay) -> {this, function, will, be, removed, SomeDay}.
According to **Xref**:
> `deprecated_functions:deprecated/1` is deprecated

2015-03-05 20:02 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +good() ->
According to **Xref**:
> `ignore_xref:good/0` is an unused export

2015-03-05 20:02 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `ignore_xref:internal/0` is deprecated

2015-03-05 20:02 UTC, gadgetci commented on src/xref/exports_not_used.erl
> +export_not(Used) -> local(Used), {it, is, not Used}.
According to **Xref**:
> `exports_not_used:export_not/1` is an unused export

2015-03-05 20:02 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated() -> {this, function, is, deprecated}.
According to **Xref**:
> `deprecated_functions:deprecated/0` is deprecated

2015-03-05 20:02 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` calls deprecated function `deprecated_function_calls:internal/0`

2015-03-05 20:02 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +good() ->
According to **Xref**:
> `deprecated_function_calls:good/0` is an unused export

2015-03-05 20:02 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad() ->
According to **Xref**:
> `undefined_functions:bad/0` calls undefined function `undefined_functions:undefined_here/0`

2015-03-05 20:02 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad(1) ->
According to **Xref**:
> `ignore_xref:bad/1` is an unused export

2015-03-05 20:02 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` is an unused export

2015-03-05 20:02 UTC, gadgetci commented
According to **Xref**:
> `undefined_functions:undefined_there/0` is not defined as a function

2015-03-05 20:02 UTC, gadgetci commented on src/org_warning.erl
> +my_fun(X) ->
According to **Xref**:
> `org_warning:my_fun/1` is an unused export

2015-03-05 20:03 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` calls deprecated function `deprecated_functions:deprecated/1`

2015-03-05 20:03 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad(1) ->
According to **Xref**:
> `ignore_xref:bad/1` calls deprecated function `ignore_xref:internal/0`

2015-03-05 20:03 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad(1) ->
According to **Xref**:
> `undefined_functions:bad/1` calls undefined function `other_module:undefined_somewhere_else/1`

2015-03-05 20:03 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad() ->
According to **Xref**:
> `undefined_functions:bad/0` is an unused export

2015-03-05 20:03 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `undefined_function_calls:bad/1` calls undefined function `undefined_functions:undefined_there/0`

2015-03-05 20:03 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad() ->
According to **Xref**:
> `ignore_xref:bad/0` is an unused export

2015-03-05 20:03 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad(1) ->
According to **Xref**:
> `undefined_functions:bad/1` calls undefined function `other_module:undefined_somewhere_else/0`

2015-03-05 20:03 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad() ->
According to **Xref**:
> `deprecated_function_calls:bad/0` calls deprecated function `deprecated_functions:deprecated/0`

2015-03-05 20:03 UTC, gadgetci commented on src/org.erl
> +stop() -> application:stop(org).
According to **Xref**:
> `org:stop/0` is an unused export

2015-03-05 20:56 UTC, gadgetci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2015-03-05 20:56 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
Warning: function local_not/1 is unused

2015-03-05 20:56 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` calls deprecated function `deprecated_function_calls:internal/0`

2015-03-05 20:56 UTC, gadgetci commented on src/org_warning.erl
> +my_fun(X) ->
According to **Xref**:
> `org_warning:my_fun/1` is an unused export

2015-03-05 20:56 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad() ->
According to **Xref**:
> `undefined_functions:bad/0` is an unused export

2015-03-05 20:56 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
According to **Xref**:
> `org_warning:warning/1` is an unused export

2015-03-05 20:56 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad() ->
According to **Xref**:
> `undefined_function_calls:bad/0` calls undefined function `undefined_function_calls:undefined_here/0`

2015-03-05 20:56 UTC, gadgetci commented on src/org.erl
> +stop() -> application:stop(org).
According to **Xref**:
> `org:stop/0` is an unused export

2015-03-05 20:56 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad() ->
According to **Xref**:
> `ignore_xref:bad/0` calls deprecated function `deprecated_functions:deprecated/0`

2015-03-05 20:56 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad(1) ->
According to **Xref**:
> `ignore_xref:bad/1` calls deprecated function `ignore_xref:internal/0`

2015-03-05 20:56 UTC, gadgetci commented on src/xref/exports_not_used.erl
> +export_not(Used) -> local(Used), {it, is, not Used}.
According to **Xref**:
> `exports_not_used:export_not/1` is an unused export

2015-03-05 20:56 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `undefined_function_calls:bad/1` calls undefined function `undefined_functions:undefined_there/0`

2015-03-05 20:56 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad() ->
According to **Xref**:
> `undefined_functions:bad/0` calls undefined function `undefined_functions:undefined_here/0`

2015-03-05 20:56 UTC, gadgetci commented
According to **Xref**:
> `undefined_function_calls:undefined_here/0` is not defined as a function

2015-03-05 20:57 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad(1) ->
According to **Xref**:
> `undefined_functions:bad/1` calls undefined function `other_module:undefined_somewhere_else/0`

2015-03-05 20:57 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated(SomeDay) -> {this, function, will, be, removed, SomeDay}.
According to **Xref**:
> `deprecated_functions:deprecated/1` is deprecated

2015-03-05 20:57 UTC, gadgetci commented
According to **Xref**:
> `undefined_functions:undefined_there/0` is not defined as a function

2015-03-05 20:57 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` is an unused export

2015-03-05 20:57 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad() ->
According to **Xref**:
> `ignore_xref:bad/0` is an unused export

2015-03-05 20:57 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad() ->
According to **Xref**:
> `undefined_function_calls:bad/0` is an unused export

2015-03-05 20:57 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` calls deprecated function `deprecated_functions:deprecated/1`

2015-03-05 20:57 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad() ->
According to **Xref**:
> `deprecated_function_calls:bad/0` calls deprecated function `deprecated_functions:deprecated/0`

2015-03-05 20:57 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad() ->
According to **Xref**:
> `deprecated_function_calls:bad/0` is an unused export

2015-03-05 20:57 UTC, gadgetci commented
According to **Xref**:
> `undefined_functions:undefined_here/0` is not defined as a function

2015-03-05 20:58 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated() -> {this, function, is, deprecated}.
According to **Xref**:
> `deprecated_functions:deprecated/0` is deprecated

2015-03-05 20:58 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad(1) ->
According to **Xref**:
> `undefined_functions:bad/1` calls undefined function `other_module:undefined_somewhere_else/1`

2015-03-05 20:58 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +good() ->
According to **Xref**:
> `ignore_xref:good/0` is an unused export

2015-03-05 20:58 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `deprecated_function_calls:internal/0` is deprecated

2015-03-05 20:58 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Xref**:
> `locals_not_used:local_not/1` is an unused local function

2015-03-05 20:58 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
Warning: variable 'Something' is unused

2015-03-05 20:58 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad(1) ->
According to **Xref**:
> `ignore_xref:bad/1` is an unused export

2015-03-05 20:58 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `undefined_function_calls:bad/1` calls undefined function `other_module:undefined_somewhere_else/1`

2015-03-05 20:58 UTC, gadgetci commented on src/org.erl
> +start() -> application:ensure_all_started(org).
According to **Xref**:
> `org:start/0` is an unused export

2015-03-05 20:58 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +exported() -> local(true), {it, is, exports_not_used:exported()}.
According to **Xref**:
> `locals_not_used:exported/0` is an unused export

2015-03-05 20:58 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `ignore_xref:internal/0` is deprecated

2015-03-05 20:58 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +good() ->
According to **Xref**:
> `deprecated_function_calls:good/0` is an unused export

2015-03-09 20:27 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +  undefined_functions:undefined_here(),
According to **Dialyzer**:
> undefined_functions.erl:6: Call to missing or unexported function undefined_functions:undefined_here/0

2015-03-09 20:27 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +  undefined_function_calls:undefined_here(),
According to **Dialyzer**:
> undefined_function_calls.erl:6: Call to missing or unexported function undefined_function_calls:undefined_here/0

2015-03-09 20:27 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Dialyzer**:
> locals_not_used.erl:9: Function local_not/1 will never be called

2015-03-09 20:27 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +  undefined_functions:undefined_there(),
According to **Dialyzer**:
> undefined_function_calls.erl:10: Call to missing or unexported function undefined_functions:undefined_there/0

2015-03-09 20:40 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +  undefined_function_calls:undefined_here(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_function_callsundefined_here/0

2015-03-09 20:40 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +  undefined_functions:undefined_there(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_functionsundefined_there/0

2015-03-09 20:40 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Dialyzer**:
>  Function local_not/1 will never be called

2015-03-09 20:40 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +  undefined_functions:undefined_here(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_functionsundefined_here/0

2015-03-09 20:47 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Dialyzer**:
>  Function local_not/1 will never be called

2015-03-09 20:47 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +  undefined_functions:undefined_there(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_functions:undefined_there/0

2015-03-09 20:47 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +  undefined_function_calls:undefined_here(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_function_calls:undefined_here/0

2015-03-09 20:47 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +  undefined_functions:undefined_here(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_functions:undefined_here/0

2015-03-10 12:52 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
Warning: variable 'Something' is unused

2015-03-10 12:52 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
Warning: function local_not/1 is unused

2015-03-10 14:22 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Xref**:
> `locals_not_used:local_not/1` is an unused local function

2015-03-10 14:22 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad(1) ->
According to **Xref**:
> `undefined_functions:bad/1` calls undefined function `other_module:undefined_somewhere_else/0`

2015-03-10 14:22 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` calls deprecated function `deprecated_functions:deprecated/1`

2015-03-10 14:22 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated(SomeDay) -> {this, function, will, be, removed, SomeDay}.
According to **Xref**:
> `deprecated_functions:deprecated/1` is deprecated

2015-03-10 14:22 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad() ->
According to **Xref**:
> `undefined_function_calls:bad/0` calls undefined function `undefined_function_calls:undefined_here/0`

2015-03-10 14:22 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `undefined_function_calls:bad/1` calls undefined function `undefined_functions:undefined_there/0`

2015-03-10 14:22 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `undefined_function_calls:bad/1` calls undefined function `other_module:undefined_somewhere_else/1`

2015-03-10 14:22 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad() ->
According to **Xref**:
> `undefined_function_calls:bad/0` is an unused export

2015-03-10 14:22 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad() ->
According to **Xref**:
> `deprecated_function_calls:bad/0` is an unused export

2015-03-10 14:22 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad(1) ->
According to **Xref**:
> `ignore_xref:bad/1` is an unused export

2015-03-10 14:22 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` calls deprecated function `deprecated_function_calls:internal/0`

2015-03-10 14:22 UTC, gadgetci commented
According to **Xref**:
> `undefined_functions:undefined_here/0` is not defined as a function

2015-03-10 14:22 UTC, gadgetci commented
According to **Xref**:
> `undefined_functions:undefined_there/0` is not defined as a function

2015-03-10 14:22 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +good() ->
According to **Xref**:
> `deprecated_function_calls:good/0` is an unused export

2015-03-10 14:22 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad() ->
According to **Xref**:
> `undefined_functions:bad/0` is an unused export

2015-03-10 14:22 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad(1) ->
According to **Xref**:
> `ignore_xref:bad/1` calls deprecated function `ignore_xref:internal/0`

2015-03-10 14:22 UTC, gadgetci commented on src/xref/exports_not_used.erl
> +export_not(Used) -> local(Used), {it, is, not Used}.
According to **Xref**:
> `exports_not_used:export_not/1` is an unused export

2015-03-10 14:22 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated() -> {this, function, is, deprecated}.
According to **Xref**:
> `deprecated_functions:deprecated/0` is deprecated

2015-03-10 14:22 UTC, gadgetci commented on src/org_warning.erl
> +my_fun(X) ->
According to **Xref**:
> `org_warning:my_fun/1` is an unused export

2015-03-10 14:22 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` is an unused export

2015-03-10 14:22 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +exported() -> local(true), {it, is, exports_not_used:exported()}.
According to **Xref**:
> `locals_not_used:exported/0` is an unused export

2015-03-10 14:22 UTC, gadgetci commented on src/org.erl
> +stop() -> application:stop(org).
According to **Xref**:
> `org:stop/0` is an unused export

2015-03-10 14:22 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad() ->
According to **Xref**:
> `undefined_functions:bad/0` calls undefined function `undefined_functions:undefined_here/0`

2015-03-10 14:22 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad() ->
According to **Xref**:
> `ignore_xref:bad/0` calls deprecated function `deprecated_functions:deprecated/0`

2015-03-10 14:23 UTC, gadgetci commented
According to **Xref**:
> `undefined_function_calls:undefined_here/0` is not defined as a function

2015-03-10 14:23 UTC, gadgetci commented on src/org.erl
> +start() -> application:ensure_all_started(org).
According to **Xref**:
> `org:start/0` is an unused export

2015-03-10 14:23 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad() ->
According to **Xref**:
> `deprecated_function_calls:bad/0` calls deprecated function `deprecated_functions:deprecated/0`

2015-03-10 14:23 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad() ->
According to **Xref**:
> `ignore_xref:bad/0` is an unused export

2015-03-10 14:23 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +good() ->
According to **Xref**:
> `ignore_xref:good/0` is an unused export

2015-03-10 14:23 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `deprecated_function_calls:internal/0` is deprecated

2015-03-10 14:23 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad(1) ->
According to **Xref**:
> `undefined_functions:bad/1` calls undefined function `other_module:undefined_somewhere_else/1`

2015-03-10 14:23 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
According to **Xref**:
> `org_warning:warning/1` is an unused export

2015-03-10 14:23 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `ignore_xref:internal/0` is deprecated

2015-03-10 17:12 UTC, gadgetci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2015-03-10 17:12 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated() -> {this, function, is, deprecated}.
According to **Xref**:
> `deprecated_functions:deprecated/0` is deprecated

2015-03-10 17:12 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
Warning: function local_not/1 is unused

2015-03-10 17:12 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad() ->
According to **Xref**:
> `undefined_functions:bad/0` is an unused export

2015-03-10 17:12 UTC, gadgetci commented on src/org.erl
> +start() -> application:ensure_all_started(org).
According to **Xref**:
> `org:start/0` is an unused export

2015-03-10 17:12 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad() ->
According to **Xref**:
> `ignore_xref:bad/0` is an unused export

2015-03-10 17:12 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad() ->
According to **Xref**:
> `undefined_function_calls:bad/0` is an unused export

2015-03-10 17:12 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
Warning: variable 'Something' is unused

2015-03-10 17:12 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `deprecated_function_calls:internal/0` is deprecated

2015-03-10 17:12 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad() ->
According to **Xref**:
> `undefined_function_calls:bad/0` calls undefined function `undefined_function_calls:undefined_here/0`

2015-03-10 17:12 UTC, gadgetci commented on src/org.erl
> +stop() -> application:stop(org).
According to **Xref**:
> `org:stop/0` is an unused export

2015-03-10 17:12 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` is an unused export

2015-03-10 17:12 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad(1) ->
According to **Xref**:
> `ignore_xref:bad/1` is an unused export

2015-03-10 17:12 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad(1) ->
According to **Xref**:
> `undefined_functions:bad/1` calls undefined function `other_module:undefined_somewhere_else/1`

2015-03-10 17:12 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` calls deprecated function `deprecated_functions:deprecated/1`

2015-03-10 17:12 UTC, gadgetci commented on src/org_warning.erl
> +my_fun(X) ->
According to **Xref**:
> `org_warning:my_fun/1` is an unused export

2015-03-10 17:12 UTC, gadgetci commented
According to **Xref**:
> `undefined_function_calls:undefined_here/0` is not defined as a function

2015-03-10 17:12 UTC, gadgetci commented
According to **Xref**:
> `undefined_functions:undefined_there/0` is not defined as a function

2015-03-10 17:12 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
According to **Xref**:
> `org_warning:warning/1` is an unused export

2015-03-10 17:12 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` calls deprecated function `deprecated_function_calls:internal/0`

2015-03-10 17:12 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +good() ->
According to **Xref**:
> `ignore_xref:good/0` is an unused export

2015-03-10 17:12 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +good() ->
According to **Xref**:
> `deprecated_function_calls:good/0` is an unused export

2015-03-10 17:12 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Xref**:
> `locals_not_used:local_not/1` is an unused local function

2015-03-10 17:12 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad() ->
According to **Xref**:
> `ignore_xref:bad/0` calls deprecated function `deprecated_functions:deprecated/0`

2015-03-10 17:13 UTC, gadgetci commented on src/xref/exports_not_used.erl
> +export_not(Used) -> local(Used), {it, is, not Used}.
According to **Xref**:
> `exports_not_used:export_not/1` is an unused export

2015-03-10 17:13 UTC, gadgetci commented
According to **Xref**:
> `undefined_functions:undefined_here/0` is not defined as a function

2015-03-10 17:13 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad() ->
According to **Xref**:
> `undefined_functions:bad/0` calls undefined function `undefined_functions:undefined_here/0`

2015-03-10 17:13 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `ignore_xref:internal/0` is deprecated

2015-03-10 17:13 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad() ->
According to **Xref**:
> `deprecated_function_calls:bad/0` is an unused export

2015-03-10 17:13 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad() ->
According to **Xref**:
> `deprecated_function_calls:bad/0` calls deprecated function `deprecated_functions:deprecated/0`

2015-03-10 17:13 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +exported() -> local(true), {it, is, exports_not_used:exported()}.
According to **Xref**:
> `locals_not_used:exported/0` is an unused export

2015-03-10 17:13 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated(SomeDay) -> {this, function, will, be, removed, SomeDay}.
According to **Xref**:
> `deprecated_functions:deprecated/1` is deprecated

2015-03-10 17:13 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `undefined_function_calls:bad/1` calls undefined function `undefined_functions:undefined_there/0`

2015-03-10 17:13 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad(1) ->
According to **Xref**:
> `ignore_xref:bad/1` calls deprecated function `ignore_xref:internal/0`

2015-03-10 17:13 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad(1) ->
According to **Xref**:
> `undefined_functions:bad/1` calls undefined function `other_module:undefined_somewhere_else/0`

2015-03-10 17:13 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `undefined_function_calls:bad/1` calls undefined function `other_module:undefined_somewhere_else/1`

2015-03-10 17:14 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Dialyzer**:
>  Function local_not/1 will never be called

2015-03-10 17:14 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +  undefined_function_calls:undefined_here(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_function_calls:undefined_here/0

2015-03-10 17:14 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +  undefined_functions:undefined_here(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_functions:undefined_here/0

2015-03-10 17:14 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +  undefined_functions:undefined_there(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_functions:undefined_there/0

2015-03-12 04:12 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Dialyzer**:
>  Function local_not/1 will never be called

2015-03-12 04:12 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +  undefined_functions:undefined_there(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_functions:undefined_there/0

2015-03-12 04:12 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +  undefined_functions:undefined_here(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_functions:undefined_here/0

2015-03-12 04:12 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +  undefined_function_calls:undefined_here(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_function_calls:undefined_here/0

2015-03-18 14:38 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +  undefined_function_calls:undefined_here(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_function_calls:undefined_here/0

2015-03-18 14:38 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +  undefined_functions:undefined_there(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_functions:undefined_there/0

2015-03-18 14:38 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +  undefined_functions:undefined_here(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_functions:undefined_here/0

2015-03-18 14:38 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Dialyzer**:
>  Function local_not/1 will never be called

2015-03-18 14:41 UTC, gadgetci commented on src/org.erl
> +start() -> application:ensure_all_started(org).
According to **Xref**:
> `org:start/0` is an unused export

2015-03-18 14:41 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +exported() -> local(true), {it, is, exports_not_used:exported()}.
According to **Xref**:
> `locals_not_used:exported/0` is an unused export

2015-03-18 14:41 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad() ->
According to **Xref**:
> `undefined_functions:bad/0` calls undefined function `undefined_functions:undefined_here/0`

2015-03-18 14:41 UTC, gadgetci commented on src/xref/exports_not_used.erl
> +export_not(Used) -> local(Used), {it, is, not Used}.
According to **Xref**:
> `exports_not_used:export_not/1` is an unused export

2015-03-18 14:41 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `ignore_xref:internal/0` is deprecated

2015-03-18 14:41 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +good() ->
According to **Xref**:
> `deprecated_function_calls:good/0` is an unused export

2015-03-18 14:41 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` calls deprecated function `deprecated_function_calls:internal/0`

2015-03-18 14:41 UTC, gadgetci commented
According to **Xref**:
> `undefined_functions:undefined_here/0` is not defined as a function

2015-03-18 14:41 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad() ->
According to **Xref**:
> `undefined_function_calls:bad/0` calls undefined function `undefined_function_calls:undefined_here/0`

2015-03-18 14:41 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad() ->
According to **Xref**:
> `deprecated_function_calls:bad/0` calls deprecated function `deprecated_functions:deprecated/0`

2015-03-18 14:41 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` is an unused export

2015-03-18 14:41 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad() ->
According to **Xref**:
> `undefined_function_calls:bad/0` is an unused export

2015-03-18 14:41 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` calls deprecated function `deprecated_functions:deprecated/1`

2015-03-18 14:41 UTC, gadgetci commented
According to **Xref**:
> `undefined_function_calls:undefined_here/0` is not defined as a function

2015-03-18 14:41 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad() ->
According to **Xref**:
> `ignore_xref:bad/0` is an unused export

2015-03-18 14:41 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad() ->
According to **Xref**:
> `ignore_xref:bad/0` calls deprecated function `deprecated_functions:deprecated/0`

2015-03-18 14:41 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad(1) ->
According to **Xref**:
> `undefined_functions:bad/1` calls undefined function `other_module:undefined_somewhere_else/1`

2015-03-18 14:41 UTC, gadgetci commented on src/org_warning.erl
> +my_fun(X) ->
According to **Xref**:
> `org_warning:my_fun/1` is an unused export

2015-03-18 14:41 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +internal() -> {this, is, deprecated}.
According to **Xref**:
> `deprecated_function_calls:internal/0` is deprecated

2015-03-18 14:41 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +good() ->
According to **Xref**:
> `ignore_xref:good/0` is an unused export

2015-03-18 14:41 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `undefined_function_calls:bad/1` calls undefined function `other_module:undefined_somewhere_else/1`

2015-03-18 14:41 UTC, gadgetci commented on src/org.erl
> +stop() -> application:stop(org).
According to **Xref**:
> `org:stop/0` is an unused export

2015-03-18 14:41 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Xref**:
> `locals_not_used:local_not/1` is an unused local function

2015-03-18 14:41 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad(1) ->
According to **Xref**:
> `ignore_xref:bad/1` calls deprecated function `ignore_xref:internal/0`

2015-03-18 14:42 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated() -> {this, function, is, deprecated}.
According to **Xref**:
> `deprecated_functions:deprecated/0` is deprecated

2015-03-18 14:42 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad() ->
According to **Xref**:
> `deprecated_function_calls:bad/0` is an unused export

2015-03-18 14:43 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
According to **Xref**:
> `org_warning:warning/1` is an unused export

2015-03-18 14:43 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad(1) ->
According to **Xref**:
> `ignore_xref:bad/1` is an unused export

2015-03-18 14:43 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `undefined_function_calls:bad/1` calls undefined function `undefined_functions:undefined_there/0`

2015-03-18 14:43 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad(1) ->
According to **Xref**:
> `undefined_functions:bad/1` calls undefined function `other_module:undefined_somewhere_else/0`

2015-03-18 14:43 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad() ->
According to **Xref**:
> `undefined_functions:bad/0` is an unused export

2015-03-18 14:43 UTC, gadgetci commented
According to **Xref**:
> `undefined_functions:undefined_there/0` is not defined as a function

2015-03-18 14:43 UTC, gadgetci commented on src/xref/deprecated_functions.erl
> +deprecated(SomeDay) -> {this, function, will, be, removed, SomeDay}.
According to **Xref**:
> `deprecated_functions:deprecated/1` is deprecated

2015-03-18 14:48 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **the compiler**:
> Warning: function local_not/1 is unused

2015-03-18 14:48 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
According to **the compiler**:
> Warning: variable 'Something' is unused

2015-03-18 17:03 UTC, gadgetci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
According to **Elvis**:
> Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2015-03-23 12:40 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Compiler**:
> Warning: function local_not/1 is unused

2015-03-23 12:40 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
According to **Compiler**:
> Warning: variable 'Something' is unused

2015-03-23 12:54 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
According to **Compiler**:
> Warning: variable 'Something' is unused

2015-03-23 12:54 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Compiler**:
> Warning: function local_not/1 is unused

2015-04-07 19:25 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
According to **Compiler**:
> Warning: variable 'Something' is unused

2015-04-07 19:25 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Compiler**:
> Warning: function local_not/1 is unused

2015-04-07 20:02 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Compiler**:
> Warning: function local_not/1 is unused

2015-04-07 20:02 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
According to **Compiler**:
> Warning: variable 'Something' is unused

2015-04-07 20:26 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Compiler**:
> Warning: function local_not/1 is unused

2015-04-07 20:26 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
According to **Compiler**:
> Warning: variable 'Something' is unused

2015-04-07 20:30 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Compiler**:
> Warning: function local_not/1 is unused

2015-04-07 20:30 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
According to **Compiler**:
> Warning: variable 'Something' is unused

2015-04-07 20:31 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Compiler**:
> Warning: function local_not/1 is unused

2015-04-07 20:31 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
According to **Compiler**:
> Warning: variable 'Something' is unused

2015-04-08 14:41 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Compiler**:
> Warning: function local_not/1 is unused

2015-04-08 14:41 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
According to **Compiler**:
> Warning: variable 'Something' is unused

2015-04-08 14:43 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Compiler**:
> Warning: function local_not/1 is unused

2015-04-08 14:43 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
According to **Compiler**:
> Warning: variable 'Something' is unused

2015-04-08 15:00 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
According to **Compiler**:
> Warning: variable 'Something' is unused

2015-04-08 15:00 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Compiler**:
> Warning: function local_not/1 is unused

2015-04-08 15:29 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Compiler**:
> Warning: function local_not/1 is unused

2015-04-08 15:29 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
According to **Compiler**:
> Warning: variable 'Something' is unused

2015-04-08 15:31 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Dialyzer**:
>  Function local_not/1 will never be called

2015-04-08 15:31 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +  undefined_functions:undefined_here(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_functions:undefined_here/0

2015-04-08 15:31 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +  undefined_functions:undefined_there(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_functions:undefined_there/0

2015-04-08 15:31 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +  undefined_function_calls:undefined_here(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_function_calls:undefined_here/0

2015-04-10 19:12 UTC, gadgetci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
According to **Elvis**:
> Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2015-04-10 19:13 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `undefined_function_calls:bad/1` calls undefined function `other_module:undefined_somewhere_else/1`

2015-04-10 19:13 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` calls deprecated function `deprecated_functions:deprecated/1`

2015-04-10 19:13 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` calls deprecated function `deprecated_function_calls:internal/0`

2015-04-10 19:13 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad(1) ->
According to **Xref**:
> `ignore_xref:bad/1` calls deprecated function `ignore_xref:internal/0`

2015-04-10 19:13 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Compiler**:
> Warning: function local_not/1 is unused

2015-04-10 19:13 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad() ->
According to **Xref**:
> `ignore_xref:bad/0` calls deprecated function `deprecated_functions:deprecated/0`

2015-04-10 19:13 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `undefined_function_calls:bad/1` calls undefined function `undefined_functions:undefined_there/0`

2015-04-10 19:13 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad(1) ->
According to **Xref**:
> `undefined_functions:bad/1` calls undefined function `other_module:undefined_somewhere_else/1`

2015-04-10 19:13 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Xref**:
> `locals_not_used:local_not/1` is an unused local function

2015-04-10 19:13 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad() ->
According to **Xref**:
> `deprecated_function_calls:bad/0` calls deprecated function `deprecated_functions:deprecated/0`

2015-04-10 19:13 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad() ->
According to **Xref**:
> `undefined_function_calls:bad/0` calls undefined function `undefined_function_calls:undefined_here/0`

2015-04-10 19:13 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
According to **Compiler**:
> Warning: variable 'Something' is unused

2015-04-10 19:13 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad() ->
According to **Xref**:
> `undefined_functions:bad/0` calls undefined function `undefined_functions:undefined_here/0`

2015-04-10 19:13 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad(1) ->
According to **Xref**:
> `undefined_functions:bad/1` calls undefined function `other_module:undefined_somewhere_else/0`

2015-04-10 19:15 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Dialyzer**:
>  Function local_not/1 will never be called

2015-04-10 19:15 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +  undefined_functions:undefined_there(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_functions:undefined_there/0

2015-04-10 19:15 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +  undefined_function_calls:undefined_here(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_function_calls:undefined_here/0

2015-04-10 19:15 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +  undefined_functions:undefined_here(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_functions:undefined_here/0

2015-12-14 17:32 UTC, gadgetci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
According to **Elvis**:
> Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2016-01-04 13:11 UTC, gadgetci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
According to **Elvis**:
> Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2016-01-04 13:11 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Compiler**:
> Warning: function local_not/1 is unused

2016-01-04 13:11 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` calls deprecated function `deprecated_function_calls:internal/0`

2016-01-04 13:11 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `undefined_function_calls:bad/1` calls undefined function `undefined_functions:undefined_there/0`

2016-01-04 13:11 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad() ->
According to **Xref**:
> `undefined_function_calls:bad/0` calls undefined function `undefined_function_calls:undefined_here/0`

2016-01-04 13:11 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad() ->
According to **Xref**:
> `ignore_xref:bad/0` calls deprecated function `deprecated_functions:deprecated/0`

2016-01-04 13:11 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` calls deprecated function `deprecated_functions:deprecated/1`

2016-01-04 13:11 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
According to **Compiler**:
> Warning: variable 'Something' is unused

2016-01-04 13:11 UTC, gadgetci commented on src/xref/ignore_xref.erl
> +bad(1) ->
According to **Xref**:
> `ignore_xref:bad/1` calls deprecated function `ignore_xref:internal/0`

2016-01-04 13:11 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad(1) ->
According to **Xref**:
> `undefined_functions:bad/1` calls undefined function `other_module:undefined_somewhere_else/0`

2016-01-04 13:11 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad(1) ->
According to **Xref**:
> `undefined_functions:bad/1` calls undefined function `other_module:undefined_somewhere_else/1`

2016-01-04 13:11 UTC, gadgetci commented on src/xref/deprecated_function_calls.erl
> +bad() ->
According to **Xref**:
> `deprecated_function_calls:bad/0` calls deprecated function `deprecated_functions:deprecated/0`

2016-01-04 13:11 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `undefined_function_calls:bad/1` calls undefined function `other_module:undefined_somewhere_else/1`

2016-01-04 13:11 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +bad() ->
According to **Xref**:
> `undefined_functions:bad/0` calls undefined function `undefined_functions:undefined_here/0`

2016-01-04 13:11 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Xref**:
> `locals_not_used:local_not/1` is an unused local function

2016-01-04 13:13 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Dialyzer**:
>  Function local_not/1 will never be called

2016-01-04 13:13 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +  undefined_function_calls:undefined_here(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_function_calls:undefined_here/0

2016-01-04 13:13 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +  undefined_functions:undefined_here(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_functions:undefined_here/0

2016-01-04 13:13 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +  undefined_functions:undefined_there(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_functions:undefined_there/0

2016-01-04 13:19 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +  undefined_functions:undefined_here(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_functions:undefined_here/0

2016-01-04 13:19 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Dialyzer**:
>  Function local_not/1 will never be called

2016-01-04 13:19 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +  undefined_functions:undefined_there(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_functions:undefined_there/0

2016-01-04 13:19 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +  undefined_function_calls:undefined_here(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_function_calls:undefined_here/0

2017-06-01 18:26 UTC, elvisci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2017-06-01 18:38 UTC, elvisci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2017-06-01 18:41 UTC, gadgetci commented
According to **Elvis**:
> The current Elvis configuration file has an outdated format. Please check Elvis's GitHub repository to find out what the new format is.

2017-06-01 18:41 UTC, gadgetci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
According to **Elvis**:
> Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2017-06-01 18:43 UTC, gadgetci commented on Makefile
> +dep_eper = git git://github.com/massemanet/eper.git 0.90.0
According to **Compiler**:
> recipe for target 'compile' failed

2017-06-01 18:43 UTC, gadgetci commented on erlang.mk
> +mib_verbose_0 = @echo " MIB   " $(filter %.bin %.mib,$(?F));
According to **Compiler**:
> recipe for target 'ebin/katana.app' failed

2017-06-01 18:43 UTC, gadgetci commented on src/org_warning.erl
> +warning(Something) -> unused.
According to **Compiler**:
> Warning: variable 'Something' is unused

2017-06-01 18:43 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Compiler**:
> Warning: function local_not/1 is unused

2017-06-01 18:45 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +  undefined_function_calls:undefined_here(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_function_calls:undefined_here/0

2017-06-01 18:45 UTC, gadgetci commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Dialyzer**:
>  Function local_not/1 will never be called

2017-06-01 18:45 UTC, gadgetci commented on src/xref/undefined_function_calls.erl
> +  undefined_functions:undefined_there(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_functions:undefined_there/0

2017-06-01 18:45 UTC, gadgetci commented on src/xref/undefined_functions.erl
> +  undefined_functions:undefined_here(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_functions:undefined_here/0

2017-06-02 19:16 UTC, elvisci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2017-06-02 19:16 UTC, gadgetci-staging commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
According to **Elvis**:
> Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2017-06-02 19:16 UTC, gadgetci-staging commented
According to **Elvis**:
> The current Elvis configuration file has an outdated format. Please check Elvis's GitHub repository to find out what the new format is.

2017-06-02 19:16 UTC, gadgetci-staging commented on src/org_warning.erl
> +warning(Something) -> unused.
According to **Compiler**:
> Warning: variable 'Something' is unused

2017-06-02 19:16 UTC, gadgetci-staging commented on src/xref/ignore_xref.erl
> +bad(1) ->
According to **Xref**:
> `ignore_xref:bad/1` calls deprecated function `ignore_xref:internal/0`

2017-06-02 19:16 UTC, gadgetci-staging commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` calls deprecated function `deprecated_function_calls:internal/0`

2017-06-02 19:16 UTC, gadgetci-staging commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `undefined_function_calls:bad/1` calls undefined function `undefined_functions:undefined_there/0`

2017-06-02 19:16 UTC, gadgetci-staging commented on src/xref/undefined_functions.erl
> +bad() ->
According to **Xref**:
> `undefined_functions:bad/0` calls undefined function `undefined_functions:undefined_here/0`

2017-06-02 19:16 UTC, gadgetci-staging commented on src/xref/undefined_functions.erl
> +bad(1) ->
According to **Xref**:
> `undefined_functions:bad/1` calls undefined function `other_module:undefined_somewhere_else/0`

2017-06-02 19:16 UTC, gadgetci-staging commented on erlang.mk
> +mib_verbose_0 = @echo " MIB   " $(filter %.bin %.mib,$(?F));
According to **Compiler**:
> recipe for target 'ebin/katana.app' failed

2017-06-02 19:16 UTC, gadgetci-staging commented on src/xref/undefined_function_calls.erl
> +bad() ->
According to **Xref**:
> `undefined_function_calls:bad/0` calls undefined function `undefined_function_calls:undefined_here/0`

2017-06-02 19:16 UTC, gadgetci-staging commented on src/xref/undefined_functions.erl
> +bad(1) ->
According to **Xref**:
> `undefined_functions:bad/1` calls undefined function `other_module:undefined_somewhere_else/1`

2017-06-02 19:16 UTC, gadgetci-staging commented on src/xref/ignore_xref.erl
> +bad() ->
According to **Xref**:
> `ignore_xref:bad/0` calls deprecated function `deprecated_functions:deprecated/0`

2017-06-02 19:16 UTC, gadgetci-staging commented on src/xref/deprecated_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `deprecated_function_calls:bad/1` calls deprecated function `deprecated_functions:deprecated/1`

2017-06-02 19:16 UTC, gadgetci-staging commented on Makefile
> +dep_eper = git git://github.com/massemanet/eper.git 0.90.0
According to **Compiler**:
> recipe for target 'compile' failed

2017-06-02 19:16 UTC, gadgetci-staging commented on src/xref/deprecated_function_calls.erl
> +bad() ->
According to **Xref**:
> `deprecated_function_calls:bad/0` calls deprecated function `deprecated_functions:deprecated/0`

2017-06-02 19:16 UTC, gadgetci-staging commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Xref**:
> `locals_not_used:local_not/1` is an unused local function

2017-06-02 19:16 UTC, gadgetci-staging commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Compiler**:
> Warning: function local_not/1 is unused

2017-06-02 19:16 UTC, gadgetci-staging commented on src/xref/undefined_function_calls.erl
> +bad(1) ->
According to **Xref**:
> `undefined_function_calls:bad/1` calls undefined function `other_module:undefined_somewhere_else/1`

2017-06-02 19:17 UTC, gadgetci-staging commented on src/xref/undefined_function_calls.erl
> +  undefined_function_calls:undefined_here(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_function_calls:undefined_here/0

2017-06-02 19:17 UTC, gadgetci-staging commented on src/xref/undefined_function_calls.erl
> +  undefined_functions:undefined_there(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_functions:undefined_there/0

2017-06-02 19:17 UTC, gadgetci-staging commented on src/xref/locals_not_used.erl
> +local_not(Used) -> {it, is, not Used}.
According to **Dialyzer**:
>  Function local_not/1 will never be called

2017-06-02 19:17 UTC, gadgetci-staging commented on src/xref/undefined_functions.erl
> +  undefined_functions:undefined_here(),
According to **Dialyzer**:
>  Call to missing or unexported function undefined_functions:undefined_here/0

2017-06-14 13:50 UTC, elvisci commented
The current Elvis configuration file has an outdated format. Please check Elvis's GitHub repository to find out what the new format is.

2017-06-14 16:26 UTC, elvisci commented
The current Elvis configuration file has an outdated format. Please check Elvis's GitHub repository to find out what the new format is.

2017-06-14 19:51 UTC, elvisci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2017-06-22 20:36 UTC, elvisci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2017-06-22 20:36 UTC, elvisci commented
The current Elvis configuration file has an outdated format. Please check Elvis's GitHub repository to find out what the new format is.

2017-06-22 20:40 UTC, elvisci commented
The current Elvis configuration file has an outdated format. Please check Elvis's GitHub repository to find out what the new format is.

2017-06-26 22:57 UTC, elvisci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2017-06-26 22:58 UTC, elvisci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2017-06-26 22:59 UTC, elvisci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2017-06-26 23:10 UTC, elvisci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2017-06-28 17:58 UTC, elvisci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2017-07-07 20:08 UTC, elvisci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2017-07-13 19:03 UTC, elvisci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2017-07-13 20:55 UTC, elvisci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2017-07-13 20:59 UTC, elvisci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2017-07-13 21:00 UTC, elvisci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2017-07-15 00:43 UTC, elvisci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2017-07-15 00:44 UTC, elvisci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2017-07-17 17:44 UTC, elvisci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2017-07-17 18:14 UTC, elvisci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2017-07-17 18:17 UTC, elvisci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2017-07-17 18:19 UTC, elvisci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2017-07-17 18:22 UTC, elvisci submitted a review, later dismissed
- The current Elvis configuration file has an outdated format. Please check Elvis's GitHub repository to find out what the new format is.

2017-07-17 18:22 UTC, elvisci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2017-07-17 18:25 UTC, elvisci submitted a review, later dismissed
- The current Elvis configuration file has an outdated format. Please check Elvis's GitHub repository to find out what the new format is.

2017-07-17 18:25 UTC, elvisci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2017-07-17 20:31 UTC, elvisci requested changes
- The current Elvis configuration file has an outdated format. Please check Elvis's GitHub repository to find out what the new format is.

2017-07-17 20:31 UTC, elvisci commented on src/org.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2018-07-19 18:14 UTC, elbrujohalcon commented
This PR is useless now 😢

2018-07-19 18:14 UTC, closed without merging