Xref Test
gadget-test/org-repo pull request #2
Opened 2015-04-10 20:09 UTC by elbrujohalcon

2015-04-10 20:14 UTC, gadgetci commented on src/org.erl
> +start(normal, _Args) ->
According to **Xref**:
> `org:start/2` calls undefined function `lager_config:get/2`

2015-04-10 20:14 UTC, gadgetci commented on src/org.erl
> +stop(_State) ->
According to **Xref**:
> `org:stop/1` calls undefined function `lager:md/0`

2015-04-10 20:14 UTC, gadgetci commented on src/org.erl
> +stop(_State) ->
According to **Xref**:
> `org:stop/1` calls undefined function `lager_config:get/2`

2015-04-10 20:14 UTC, gadgetci commented on src/org.erl
> +start(normal, _Args) ->
According to **Xref**:
> `org:start/2` calls undefined function `lager:md/0`

2015-04-10 20:14 UTC, gadgetci commented on src/org.erl
> +start(normal, _Args) ->
According to **Xref**:
> `org:start/2` calls undefined function `lager:do_log/9`

2015-04-10 20:14 UTC, gadgetci commented on src/org.erl
> +stop(_State) ->
According to **Xref**:
> `org:stop/1` calls undefined function `lager:do_log/9`

2015-08-11 15:35 UTC, gadgetci commented on Makefile
> +
According to **Compiler**:
> warning: overriding commands for target `shell'

2016-05-06 14:12 UTC, gadgetci commented on Makefile
> +include erlang.mk
According to **Compiler**:
> warning: overriding commands for target `shell'

2016-05-06 14:12 UTC, gadgetci commented
According to **Compiler**:
> warning: ignoring old commands for target `shell'

2016-05-06 14:12 UTC, gadgetci commented on Makefile
> +include erlang.mk
According to **Compiler**:
> warning: overriding commands for target `shell'

2016-05-06 14:12 UTC, gadgetci commented
According to **Compiler**:
> warning: ignoring old commands for target `shell'

2016-05-06 14:13 UTC, gadgetci commented on Makefile
> +include erlang.mk
According to **Dialyzer**:
> warning: overriding commands for target `shell'

2016-05-06 14:13 UTC, gadgetci commented
**dialyzer** failed with exit status: 2

2016-05-06 14:13 UTC, gadgetci commented
According to **Dialyzer**:
> warning: ignoring old commands for target `shell'

2016-05-06 14:13 UTC, gadgetci commented on Makefile
> +include erlang.mk
According to **Dialyzer**:
> warning: overriding commands for target `shell'

2016-05-06 14:13 UTC, gadgetci commented
According to **Dialyzer**:
> warning: ignoring old commands for target `shell'

2017-06-01 18:55 UTC, gadgetci commented
According to **Elvis**:
> Dependency 'lager' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

2017-06-01 18:55 UTC, gadgetci commented
According to **Elvis**:
> Dependency 'katana' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

2017-06-01 18:55 UTC, gadgetci commented
According to **Elvis**:
> Dependency 'eper' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

2017-06-01 18:57 UTC, gadgetci commented on Makefile
> +include erlang.mk
According to **Compiler**:
> warning: overriding recipe for target 'shell'

2017-06-01 18:57 UTC, gadgetci commented on Makefile
> +include erlang.mk
According to **Compiler**:
> warning: overriding recipe for target 'shell'

2017-06-01 18:57 UTC, gadgetci commented
According to **Compiler**:
> warning: ignoring old recipe for target 'shell'

2017-06-01 18:57 UTC, gadgetci commented
According to **Compiler**:
> warning: ignoring old recipe for target 'shell'

2017-06-02 19:18 UTC, gadgetci-staging commented
According to **Elvis**:
> Dependency 'eper' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

2017-06-02 19:18 UTC, gadgetci-staging commented
According to **Elvis**:
> Dependency 'lager' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

2017-06-02 19:18 UTC, gadgetci-staging commented
According to **Elvis**:
> Dependency 'katana' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

2017-06-02 19:18 UTC, gadgetci-staging commented
According to **Dialyzer**:
> warning: ignoring old recipe for target 'shell'

2017-06-02 19:18 UTC, gadgetci-staging commented on Makefile
> +include erlang.mk
According to **Compiler**:
> warning: overriding recipe for target 'shell'

2017-06-02 19:18 UTC, gadgetci-staging commented on Makefile
> +include erlang.mk
According to **Dialyzer**:
> warning: overriding recipe for target 'shell'

2017-06-02 19:19 UTC, gadgetci-staging commented
According to **Compiler**:
> warning: ignoring old recipe for target 'shell'

2017-06-02 19:19 UTC, gadgetci-staging commented on Makefile
> +include erlang.mk
According to **Compiler**:
> warning: overriding recipe for target 'shell'

2017-06-02 19:19 UTC, gadgetci-staging commented
According to **Dialyzer**:
> warning: ignoring old recipe for target 'shell'

2017-06-02 19:19 UTC, gadgetci-staging commented
According to **Compiler**:
> warning: ignoring old recipe for target 'shell'

2017-06-02 19:19 UTC, gadgetci-staging commented on Makefile
> +include erlang.mk
According to **Dialyzer**:
> warning: overriding recipe for target 'shell'

2017-06-02 19:19 UTC, gadgetci-staging commented
According to **Dialyzer**:
> recipe for target '/tmp/gadget/gadget-test/org-repo/0001496-0431100-0544272/.org.plt' failed

2017-06-02 19:19 UTC, gadgetci-staging commented
**dialyzer** failed with exit status: 2

2017-06-05 13:34 UTC, gadgetci-staging commented
According to **Elvis**:
> Dependency 'katana' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

2017-06-05 13:34 UTC, gadgetci-staging commented
According to **Elvis**:
> Dependency 'lager' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

2017-06-05 13:34 UTC, gadgetci-staging commented
According to **Elvis**:
> Dependency 'eper' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

2017-06-05 13:35 UTC, gadgetci-staging commented
According to **Dialyzer**:
> recipe for target '/tmp/gadget/gadget-test/org-repo/0001496-0669679-0096819/.org.plt' failed

2017-06-05 13:35 UTC, gadgetci-staging commented
According to **Dialyzer**:
> warning: ignoring old recipe for target 'shell'

2017-06-05 13:35 UTC, gadgetci-staging commented
According to **Compiler**:
> warning: ignoring old recipe for target 'shell'

2017-06-05 13:35 UTC, gadgetci-staging commented on Makefile
> +include erlang.mk
According to **Compiler**:
> warning: overriding recipe for target 'shell'

2017-06-05 13:35 UTC, gadgetci-staging commented on Makefile
> +include erlang.mk
According to **Dialyzer**:
> warning: overriding recipe for target 'shell'

2017-06-05 13:35 UTC, gadgetci-staging commented
**dialyzer** failed with exit status: 2

2017-06-05 13:35 UTC, gadgetci-staging commented on Makefile
> +include erlang.mk
According to **Dialyzer**:
> warning: overriding recipe for target 'shell'

2017-06-05 13:35 UTC, gadgetci-staging commented on Makefile
> +include erlang.mk
According to **Compiler**:
> warning: overriding recipe for target 'shell'

2017-06-05 13:35 UTC, gadgetci-staging commented
According to **Dialyzer**:
> warning: ignoring old recipe for target 'shell'

2017-06-05 13:35 UTC, gadgetci-staging commented
According to **Compiler**:
> warning: ignoring old recipe for target 'shell'

2017-06-13 17:20 UTC, gadgetci-staging commented
According to **Elvis**:
> Dependency 'eper' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

2017-06-13 17:20 UTC, gadgetci-staging commented
According to **Elvis**:
> Dependency 'katana' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

2017-06-13 17:20 UTC, gadgetci-staging commented
According to **Elvis**:
> Dependency 'lager' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

2017-06-13 17:21 UTC, gadgetci-staging commented
**dialyzer** failed with exit status: 2

2017-06-13 17:21 UTC, gadgetci-staging commented
According to **Dialyzer**:
> warning: ignoring old recipe for target 'shell'

2017-06-13 17:21 UTC, gadgetci-staging commented
According to **Dialyzer**:
> warning: ignoring old recipe for target 'shell'

2017-06-13 17:21 UTC, gadgetci-staging commented
According to **Dialyzer**:
> recipe for target '/tmp/gadget/gadget-test/org-repo/0001497-0374434-0903756/.org.plt' failed

2017-06-13 17:21 UTC, gadgetci-staging commented
According to **Compiler**:
> warning: ignoring old recipe for target 'shell'

2017-06-13 17:21 UTC, gadgetci-staging commented on Makefile
> +include erlang.mk
According to **Compiler**:
> warning: overriding recipe for target 'shell'

2017-06-13 17:21 UTC, gadgetci-staging commented on Makefile
> +include erlang.mk
According to **Compiler**:
> warning: overriding recipe for target 'shell'

2017-06-13 17:21 UTC, gadgetci-staging commented
According to **Compiler**:
> warning: ignoring old recipe for target 'shell'

2017-06-13 17:21 UTC, gadgetci-staging commented on Makefile
> +include erlang.mk
According to **Dialyzer**:
> warning: overriding recipe for target 'shell'

2017-06-13 17:21 UTC, gadgetci-staging commented on Makefile
> +include erlang.mk
According to **Dialyzer**:
> warning: overriding recipe for target 'shell'

2017-06-13 17:31 UTC, gadgetci-staging commented
According to **Dialyzer**:
> recipe for target '/tmp/gadget/gadget-test/org-repo/0001497-0375080-0523307/.org.plt' failed

2017-06-13 17:55 UTC, gadgetci-staging commented
According to **Dialyzer**:
> recipe for target '/tmp/gadget/gadget-test/org-repo/0001497-0376486-0883145/.org.plt' failed

2017-06-13 18:44 UTC, gadgetci-staging commented
According to **Dialyzer**:
> recipe for target '/tmp/gadget/gadget-test/org-repo/0001497-0379430-0908061/.org.plt' failed

2017-06-14 01:21 UTC, gadgetci-staging commented
According to **Dialyzer**:
> recipe for target '/tmp/gadget/gadget-test/org-repo/0001497-0403264-0026004/.org.plt' failed

2017-06-14 04:07 UTC, gadgetci-staging commented
According to **Dialyzer**:
> recipe for target '/tmp/gadget/gadget-test/org-repo/0001497-0413223-0365784/.org.plt' failed

2017-06-26 23:25 UTC, elvisci submitted a review, later dismissed
Dependency 'lager' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
Dependency 'eper' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
Dependency 'katana' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

2017-06-26 23:27 UTC, elvisci submitted a review, later dismissed
- Dependency 'lager' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'eper' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'katana' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

2017-06-26 23:34 UTC, elvisci submitted a review, later dismissed
- Dependency 'lager' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'eper' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'katana' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

2017-06-27 17:06 UTC, elvisci submitted a review, later dismissed
- Dependency 'lager' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'eper' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'katana' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

2017-06-27 17:20 UTC, elvisci submitted a review, later dismissed
- Dependency 'lager' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'eper' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'katana' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

2017-06-28 15:05 UTC, elvisci submitted a review, later dismissed
- Dependency 'lager' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'eper' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'katana' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

2017-06-28 15:05 UTC, elvisci submitted a review, later dismissed
- Dependency 'lager' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'eper' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'katana' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

2017-06-28 15:07 UTC, elvisci submitted a review, later dismissed
- Dependency 'lager' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'eper' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'katana' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

2017-06-28 15:08 UTC, elvisci submitted a review, later dismissed
- Dependency 'lager' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'eper' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'katana' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

2017-06-28 15:09 UTC, elvisci submitted a review, later dismissed
- Dependency 'lager' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'eper' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'katana' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

2017-06-28 15:09 UTC, elvisci submitted a review, later dismissed
- Dependency 'lager' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'eper' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'katana' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

2017-06-28 15:12 UTC, elvisci submitted a review, later dismissed
- Dependency 'lager' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'eper' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'katana' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

2017-06-28 15:13 UTC, elvisci submitted a review, later dismissed
- Dependency 'lager' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'eper' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'katana' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

2017-06-28 15:13 UTC, elvisci requested changes
- Dependency 'lager' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'eper' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'katana' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

2018-07-19 18:14 UTC, elbrujohalcon commented
This PR is useless now 😢

2018-07-19 18:14 UTC, closed without merging